# Generated by Django 3.0.5 on 2020-05-03 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('january', models.BooleanField(default=False)),
                ('february', models.BooleanField(default=False)),
                ('march', models.BooleanField(default=False)),
                ('april', models.BooleanField(default=False)),
                ('may', models.BooleanField(default=False)),
                ('june', models.BooleanField(default=False)),
                ('july', models.BooleanField(default=False)),
                ('august', models.BooleanField(default=False)),
                ('september', models.BooleanField(default=False)),
                ('october', models.BooleanField(default=False)),
                ('november', models.BooleanField(default=False)),
                ('december', models.BooleanField(default=False)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('name', models.CharField(max_length=128)),
                ('price', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Fish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('january', models.BooleanField(default=False)),
                ('february', models.BooleanField(default=False)),
                ('march', models.BooleanField(default=False)),
                ('april', models.BooleanField(default=False)),
                ('may', models.BooleanField(default=False)),
                ('june', models.BooleanField(default=False)),
                ('july', models.BooleanField(default=False)),
                ('august', models.BooleanField(default=False)),
                ('september', models.BooleanField(default=False)),
                ('october', models.BooleanField(default=False)),
                ('november', models.BooleanField(default=False)),
                ('december', models.BooleanField(default=False)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('name', models.CharField(max_length=128)),
                ('price', models.IntegerField()),
                ('location', models.CharField(choices=[('sea', 'Sea'), ('river', 'River'), ('pier', 'Pier'), ('pond', 'Pond'), ('river-clifftop', 'River (Clifftop)')], max_length=64)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
