# Generated by Django 3.0.5 on 2020-05-03 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20200502_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fish',
            name='name',
            field=models.CharField(max_length=128, unique=True),
        ),
    ]
