# Generated by Django 3.0.5 on 2020-05-03 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20200502_1946'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bug',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='fish',
            options={'ordering': ('name',)},
        ),
        migrations.AddField(
            model_name='bug',
            name='all_day',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fish',
            name='all_day',
            field=models.BooleanField(default=False),
        ),
    ]
